### ISSUE TITLE
Endo2atom started returning empty response

### ISSUE THREAD

**Issue by toralux** [conoro/endo2atom#1]
My Endomondo profile used to work, but now it returns empty response, e.g. from my profile:
http://endo2atom.conoroneill.com/443505

**Comment by conoro** [comment]
Hi,
It looks like the problem is on the Endomondo side of things. There is nothing being returned from https://www.endomondo.com/embed/user/workouts?id=443505

As this code is 6 years old and I no longer use Endomondo, I'll mark it as deprecated.
